### ISSUE TITLE
`BaseTrainer.init_current_phase_dataset` returning two `Y_valid_cumuls`

### ISSUE THREAD

**Issue by letme-hj** [yaoyao-liu/class-incremental-learning#37]
Hi,
I'm currently looking into your neat code!

I have a simple question regarding the function `init_current_phase_dataset` of `BaseTrainer`.
It is returning `Y_valid_cumuls` twice, but I think it's supposed to return `Y_train_cumuls` instead of one of them, or maybe just erase it.
(there seems to be no other function that uses `Y_train_cumuls`, but just wanted to make sure I am correctly following your code!)

And by the way, thank you very much for your work :))

**Comment by yaoyao-liu** [comment]
Hi @letme-hj,

Thanks for your interest in our work. 

You're correct. We don't need to return `Y_train_cumuls` twice in the function `init_current_phase_dataset`.
It is because I forgot to remove it while cleaning up the code. 

This issue won't influence the following steps as well as the final results. I will fix it when I have time. 

If you have any further questions, please feel free to add more comments here or email me. Have a nice day.

Best,
Yaoyao

**Comment by letme-hj** [comment]
@yaoyao-liu Thank you for such a quick reply!
